services:
  mongodb:
    container_name: mongodb
    image: mongo:4.4

  bakeka:
    container_name: bakeka_backend
    build: .
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    environment:
      BKK_DB_HOST: mongodb
